### ISSUE TITLE
Publish imagery, POI and DEM

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/ogc-testbed#60]
Data is available under Testbed 15, files, Open Portrayal Framework, Potrayal data and sponsor input. Direct link [here](https://portal.opengeospatial.org/modules/files/details.php?m=files&artifact_id=83535).

There is a DTM in the root, and under imagery some mrsid files. We should convert them into COG before publishing. These will be used for the "WMTS-T" use case.

**Comment by aaime** [comment]
The DTM should be a hillshade, also make available a "giant polygon" with a gray fill

**Comment by aaime** [comment]
There is also a need to publish vector POIs, but it's not clear yet what do we need to publish? Should be available next week.

**Comment by aaime** [comment]
@allyoucanmap are all of these available on the server already? Can we close this ticket?

**Comment by allyoucanmap** [comment]
@aaime imagery are missing on the server

**Comment by aaime** [comment]
Ok, let's upload them on the new server directly then

**Comment by simboss** [comment]
project is closed anyway
