### ISSUE TITLE
SLD with multiple named layers generate wrong sample data

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ogc-testbed#70]
SLD with multiple named layers generate wrong sample data even if the layers are all associated to the style.
![2019-08-16 12_21_47-GeoServer_ Style Editor - vtp_night - Brave](https://user-images.githubusercontent.com/19175505/63161783-2cd32680-c021-11e9-836f-479289f6d9e8.png)

Style metadata returns the first layer sampleData for all the layer entries

**Comment by aaime** [comment]
Should have been fixed, will be in the nightly builds starting tomorrow
