### ISSUE TITLE
Tiles API Duplicate key Error

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ogc-testbed#73]
If image/png and image/png8 are available at the same time the tile is not rendered and it returns following error:

```
{
 "code": "NoApplicableCode",
 "description": "Duplicate key image/png"
}
```

configuration:

http://localhost:8080/geoserver/ogc/tiles/collections/vtp:AgricultureSrf/maps/generic/tiles/EPSG:4326/EPSG:4326:12/1306/4917/?f=image/png

![2019-09-05 16_00_41-Window](https://user-images.githubusercontent.com/19175505/64349027-79919800-cff6-11e9-8bfe-27ae4a11218a.png)

It's the same with vector format:

http://localhost:8080/geoserver/ogc/tiles/collections/vtp:AgricultureSrf/tiles/EPSG:900913/EPSG:900913:12/1655/2458??f=application/json;type=geojson

![2019-09-05 16_05_59-Window](https://user-images.githubusercontent.com/19175505/64349353-15230880-cff7-11e9-8a86-d09b7e55a2ea.png)

```
{
 "code": "NoApplicableCode",
 "description": "Duplicate key application/json"
}

```

**Comment by allyoucanmap** [comment]
I were able to visualize tiles with this configuration:

![2019-09-05 16_07_44-Window](https://user-images.githubusercontent.com/19175505/64349469-51eeff80-cff7-11e9-9f35-bd119935da4f.png)

**Comment by aaime** [comment]
Should have been fixed in the meantime, can you double check? (might need a local machine, the deploy on maps is old)

**Comment by allyoucanmap** [comment]
@aaime it's working locally both with geojson/topojson and png/png8
