### ISSUE TITLE
Tiles API wrong vector format response

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ogc-testbed#74]
If i request a tile in GeoJSON or  MVT vector format the result it's always a string as showed below.

GeoJSON
http://localhost:8080/geoserver/ogc/tiles/collections/vtp:AgricultureSrf/tiles/EPSG:900913/EPSG:900913:12/1655/2458??f=application/json;type=geojson

MVT
http://localhost:8080/geoserver/ogc/tiles/collections/vtp:AgricultureSrf/tiles/EPSG:900913/EPSG:900913:12/1655/2458??f=application/vnd.mapbox-vector-tile

Snippet of response for both formats:
```
"eyJ0eXBlIjoiRmVhdHVyZUNvbGxlY3Rpb24iLCJ0b3RhbEZlYXR1cmVzIjoidW5rbm93biIsImZlYXR1cmVzIjpbeyJ0eXBlIjoiRmVhdHVyZSIsImlkIjoiQWdyaWN1bHR1cmVTcmYuMSIsImdlb21ldHJ5Ijp7InR5cGUiOiJQb2x5Z29uIiwiY29vcmRpbmF0ZXMiOltbWzQwMTk3MTYuMiwzODQxMTcwLjM4XSxbNDAyMDAxMy4zOSwz...
```

**Comment by aaime** [comment]
The original URLs above had a double question mark. They now seem to work against maps (with single question mark):
https://backoffice-maps.geo-solutions.it/geoserver/ogc/tiles/collections/vtp:AgricultureSrf/tiles/EPSG:900913/EPSG:900913:12/1655/2458?f=application/json;type=geojson

https://backoffice-maps.geo-solutions.it/geoserver/ogc/tiles/collections/vtp:AgricultureSrf/tiles/EPSG:900913/EPSG:900913:12/1655/2458?f=application/vnd.mapbox-vector-tile

The first returns geojson, the second a valid vector tile according to "vtvalidate"
