### ISSUE TITLE
[Tiles API] Inconsistent workspace separator

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ogc-testbed#77]
In a collection request we have styles with the following id structure
`{workspace}__{styleName}`
Example:
`http://localhost:8080/geoserver/ogc/tiles/collections/vtp:Daraa_DTED`
return
```
{
    "id": "vtp:Daraa_DTED",
    "title": "Daraa_DTED",
    ...
    "styles": [
        {
            "id": "vtp__hillshade",
            "title": "Daraa_DTED",
            "links": [
                ...
            ],
            "htmlTitle": ""
        },
        ...
    ],
    ...
}
```

if we use id described above in the tiles template we get following error

`styleId` = `vtp__hillshade`
`http://localhost:8080/geoserver/ogc/tiles/collections/vtp%3ADaraa_DTED/map/vtp__hillshade/tiles/EPSG:900913/EPSG:900913:14/6619/9836?f=image%2Fpng`

```
{
  "code": "NoApplicableCode",
  "description": "Problem communicating with GeoServer\nExpected: RenderedImageMap, got null"
}
```

but if we change the separator to `:` the request returns the tile

Working request
`http://localhost:8080/geoserver/ogc/tiles/collections/vtp%3ADaraa_DTED/map/vtp:hillshade/tiles/EPSG:900913/EPSG:900913:14/6619/9836?f=image%2Fpng`

**Comment by aaime** [comment]
Should have been fixed, can you verify?
