### ISSUE TITLE
[Tiles API + Styles API] Cannot request single workspace with tiles and styles endpoint

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ogc-testbed#79]
Currently is not possible to request ogc enpoints for a specific workspace

eg:
`https://maps.geo-solutions.it/geoserver/vtp/ogc`

**Comment by aaime** [comment]
Per workspace services are available now, can you double check?

**Comment by allyoucanmap** [comment]
@aaime it working locally with workspace, we can close this
