### ISSUE TITLE
Investigate server deployment

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/ogc-testbed#85]
We should investigate the feasibility of having a specific VM for deploying work related to VTP2 to not break things developed for Testbed15.

**Comment by simboss** [comment]
This is being implemeneted by giacomo in [this](https://github.com/geosolutions-it/DevOps/issues/24) issue.

**Comment by conjame** [comment]
The setup of the machine is mostly done, the document has been moved to the [project folder](https://docs.google.com/document/d/19JSq_K09qVTLqCphbpbrMzzOK14RsgjiSUMqiU_pw3M/edit#).

I will do some review and the vm is going to be ready by tomorrow

**Comment by conjame** [comment]
@aaime The work is almost done, but I need some clarifications first.

- We noticed that the memory allocated to geoserver (4GB) is a bit too close to the server's physical memory (6GB). There is a reason for this? Should the memory allocated to geoserver be reduced?
- The jenkins job is still deploying builds from the ["ows-geoserver"](https://github.com/geosolutions-it/docker-geoserver/tree/ows-geoserver) branch, should we keep using them?

**Comment by aaime** [comment]
@giacomoc92 answers:

- Might reduce a bit, but not too much, clients might make many concurrent requests (especially those filling a geopackage). I would not go below 3GB
- I don't know about that docker image, @randomorder is probably the person you want to talk to

**Comment by randomorder** [comment]
> The jenkins job is still deploying builds from the "ows-geoserver" branch, should we keep using them?

let's make a new branch for the docker image. Can you take care of it @giacomoc92? I'd use the name of the host as the name of the branch
