### ISSUE TITLE
client side caching for demo

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/ogc-testbed#87]
[http://demo.vtp2.geo-solutions.it/index.html](http://demo.vtp2.geo-solutions.it/index.html)

Using headers in S3 and / or cloudfront

**Comment by randomorder** [comment]
![image](https://user-images.githubusercontent.com/5264230/72348668-2e417180-36db-11ea-8956-cb227685281b.png)

**Comment by aaime** [comment]
Confused, what is this? :-D

**Comment by allyoucanmap** [comment]
@aaime @randomorder I thinks it's the setup for S3 of the client demo

**Comment by randomorder** [comment]
yes. Specifically about setting HTTP response headers in S3 to tempt the client to cache static files...
