### ISSUE TITLE
[Features API] spatial filter is not applied to items

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/ogc-testbed#94]
Following cql filter `("RIN_ROI" = '3') AND (BBOX(geom,36.0603904724121,32.594696864466414,36.1424446105957,32.65773121379604))` does not returns items:

https://vtp2.geo-solutions.it/geoserver/ogc/features/collections/vtp:TransportationGroundCrv/items?f=application%2Fflatgeobuf&filter=(%22RIN_ROI%22%20%3D%20%273%27)%20AND%20(BBOX(geom%2C36.0603904724121%2C32.594696864466414%2C36.1424446105957%2C32.65773121379604))&filter-lang=cql-text

while it's working for Tiles API.
https://vtp2.geo-solutions.it/geoserver/ogc/tiles/collections/vtp%3ATransportationGroundCrv/map/vtp:transportationgroundcrv_sld/tiles/WebMercatorQuad/13/3310/4917?f=image%2Fpng&filter=(%22RIN_ROI%22%20%3D%20%273%27)%20AND%20(BBOX(geom%2C36.0603904724121%2C32.594696864466414%2C36.1424446105957%2C32.65773121379604))&filter-lang=cql-text

**Comment by aaime** [comment]
Found the issue, it's an axis order one, see https://github.com/geoserver/geoserver/pull/4057

**Comment by aaime** [comment]
@allyoucanmap can you confirm it's fixed?

**Comment by allyoucanmap** [comment]
@aaime it's fixed
